# shaders.properties
# Define the formats for our color buffers.
# RGBA16F allows colors to go above 1.0 (HDR) and doesn't compress data as much.

# colortex0: Main Color
format.color.0=RGBA16F

# colortex1: Lightmap (Default, doesn't strictly need RGBA16F, but keeping it for now if needed)
format.color.1=RGBA16F

# colortex2: Normals / Data
format.color.2=RGBA16F

# colortex3: Pushing our Volumetrics/Godrays here to use as history
format.color.3=RGBA16F

# colortex4: Translucent color buffer (for glass/water)
format.color.4=RGBA16F
